export {
  competitionKeys,
  getCompetitions,
  useCompetitionsQuery,
  getCompetitionDetail,
  useCompetitionDetailQuery,
  useRegisterCompetitionMutation,
  useUnregisterCompetitionMutation,
  useMyRegistrationsQuery,
  useCreateCompetitionMutation,
  useUpdateCompetitionMutation,
  useCreateTeamMutation,
  useDeleteTeamMutation,
  usePublishResultsMutation,
} from "./api/competitionApi";
